name: Allure Report Generation
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  fork:
    branches: [ "main" ]

  workflow_dispatch: # Trigger the workflow manually

jobs:
  generate-allure-report:
    runs-on: ubuntu-latest # Set the operating system for the job

    defaults:
      run:
        shell: bash # Set the shell for the job

    steps:
      - name: Checkout repo # Step to check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install
          npm install -g allure-commandline

      - name: Prepare Allure history # Step to prepare Allure history directory
        run: |
          mkdir -p allure-results
          cp -r ./allure-report/* allure-results/

      - name: Run tests in Chrome
        run: npm run wdio:purchase

      - name: Get Allure history # Step to retrieve Allure history
        uses: actions/checkout@v4
        if: always() # Execute even if previous steps fail
        continue-on-error: true # Continue execution even if the step fails
        with:
          ref: gh-pages # Specify the branch to retrieve Allure history from
          path: gh-pages # Set the destination path for Allure history

      - name: Allure report action # Step to generate Allure report
        uses: simple-elf/allure-report-action@master
        if: always() # Execute even if previous steps fail
        with:
          allure_results: allure-results # Specify the directory containing Allure results
          allure_history: allure-history # Specify the directory to store Allure history
          keep_reports: 5 # Specify the number of previous reports to keep

      - name: Deploy Allure report to GitHub Pages # Step to deploy Allure report to GitHub Pages
        if: always() # Execute even if previous steps fail
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_USER_TOKEN }} # Provide the GitHub token for authentication
          publish_branch: gh-pages # Specify the branch to publish the report to
          publish_dir: allure-history # Specify the directory containing the report