# This is a basic workflow to help you get started with Actions

name: SauseDemoApp Test Run

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  fork:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install dependencies
        run: npm install
          npm install -g allure-commandline
          npm i --save-dev @types/fs-extra

      - name: Run tests in Chrome
        run: npm run wdio:purchase

      - name: Generate Allure report
        run: npx allure generate --clean allure-results
        shell: bash

      - name: Upload Allure results as artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

